name: Apply unit and lint tests
on: [push, pull_request]

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      memcached:
        image: memcached:alpine
        ports: ['11211:11211']

    steps:
    - uses: actions/checkout@v4

    - name: Install additional packages
      run: |
        sudo apt-get update
        sudo apt-get install imagemagick

    - uses: actions/setup-node@v4
      with:
        cache: npm

    - run: npm install

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Setup environment
      run: ./script/gh-action-prepare

    - name: Install qlty and apply lint test
      run: |
        curl https://qlty.sh | bash
        source /home/runner/.config/.bashrc
        qlty init -n
        qlty plugins disable rubocop
        status=$(qlty check --sample=10)
        exit_code=$?

        echo "$status" | tee qlty.txt

        if [ $exit_code -ne 0 ]; then
          exit 1
        fi
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qlty.txt
        path: qlty.txt
        retention-days: 5

    - name: Lint assets
      run: npm run lint

    - name: Build assets
      run: bundle exec rails assets:precompile

    - name: Run test
      run: bundle exec rails test
